export {
    apply,
    construct,
    decorate,
    defineMetadata,
    defineProperty,
    get,
    getMetadata,
    getMetadataKeys,
    getOwnMetadata,
    getOwnMetadataKeys,
    getOwnPropertyDescriptor,
    getPrototypeOf,
    has,
    hasMetadata,
    hasOwnMetadata,
    isExtensible,
    metadata,
    ownKeys,
    preventExtensions,
    set,
    setPrototypeOf,
} from './index';
